/* Truncation of the work table */
TRUNCATE TABLE EDW_WORK.TRAC_DIM_ADDRESS;

--PARTICIPANT
/* PARTICIPANT - Select to capture insert of hist. records */
INSERT INTO EDW_WORK.TRAC_DIM_ADDRESS(DIM_ADDRESS_NATURAL_KEY_HASH_UUID, ATTENTION_LINE_TXT, ADDRESS_STREET_1_TXT, ADDRESS_STREET_2_TXT, ADDRESS_STREET_3_TXT, ADDRESS_STREET_4_TXT, CITY_NM, STATE_CDE, ZIP_CDE, ZIP_6_9_CDE, ZIP_10_13_CDE, COUNTRY_CDE, ADDRESS_VALIDATION_CDE, 
	BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, CURRENT_ROW_IND, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND)
SELECT DRVD.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, DRVD.ATTENTION_LINE_TXT, DRVD.ADDRESS_STREET_1_TXT,DRVD.ADDRESS_STREET_2_TXT,DRVD.ADDRESS_STREET_3_TXT, DRVD.ADDRESS_STREET_4_TXT,DRVD.CITY_NM,DRVD.STATE_CDE,DRVD.ZIP_CDE,DRVD.ZIP_6_9_CDE,DRVD.ZIP_10_13_CDE,DRVD.COUNTRY_CDE,DRVD.ADDRESS_VALIDATION_CDE,DRVD.BEGIN_DT, 
	DRVD.BEGIN_DTM,DRVD.ROW_PROCESS_DTM,DRVD.AUDIT_ID, DRVD.LOGICAL_DELETE_IND, DRVD.CHECK_SUM, CASE WHEN ROW_NUMBER() OVER (PARTITION BY DRVD.DIM_ADDRESS_NATURAL_KEY_HASH_UUID ORDER BY DRVD.END_DTM desc, DRVD.END_DT desc) = 1 and DRVD.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END::BOOLEAN AS CURRENT_ROW_IND,
	DRVD.END_DT, DRVD.END_DTM, DRVD.SOURCE_SYSTEM_ID, DRVD.RESTRICTED_ROW_IND
	FROM (SELECT DISTINCT UUID_GEN(PREHASH_VALUE(CLEAN_STRING(''),CLEAN_STRING(ADDRSS_LN_1), CLEAN_STRING(ADDRSS_LN_2), 
		 CLEAN_STRING(ADDRSS_LN_3), CLEAN_STRING(''),CLEAN_STRING(CITY_NM), CLEAN_STRING(SDT1.TRNSLT_FLD_VAL), CLEAN_STRING(ZIP_CD), 
		 CLEAN_STRING(ZIP_PLUS_4_CD), CLEAN_STRING(''), CLEAN_STRING(SDT2.TRNSLT_FLD_VAL)))::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID
		,CLEAN_STRING('') AS ATTENTION_LINE_TXT
		,CLEAN_STRING(ADDRSS_LN_1) AS ADDRESS_STREET_1_TXT
		,CLEAN_STRING(ADDRSS_LN_2) AS ADDRESS_STREET_2_TXT
		, CLEAN_STRING(ADDRSS_LN_3) AS ADDRESS_STREET_3_TXT
		, CLEAN_STRING('') AS ADDRESS_STREET_4_TXT
		, CLEAN_STRING(CITY_NM) AS CITY_NM
		, CLEAN_STRING(SDT1.TRNSLT_FLD_VAL) AS STATE_CDE
		, CLEAN_STRING(ZIP_CD) AS ZIP_CDE
		, CLEAN_STRING(ZIP_PLUS_4_CD) AS ZIP_6_9_CDE
		, CLEAN_STRING('') AS ZIP_10_13_CDE
		, CLEAN_STRING(SDT2.TRNSLT_FLD_VAL) AS COUNTRY_CDE
		,CLEAN_STRING('') AS ADDRESS_VALIDATION_CDE
		,HASH_GEN(PREHASH_VALUE(CLEAN_STRING('')))::UUID AS CHECK_SUM
		,RCRD_EFFCTV_DT::TIMESTAMP as BEGIN_DTM
		,RCRD_EFFCTV_DT::DATE as BEGIN_DT
		,CURRENT_TIMESTAMP as ROW_PROCESS_DTM
		,ADT.audit_id as AUDIT_ID
	    ,'203' as SOURCE_SYSTEM_ID
		,'F'::boolean as RESTRICTED_ROW_IND
		,'F'::boolean as LOGICAL_DELETE_IND
		,COALESCE(RCRD_TRM_DT,'9999-12-31')::DATE as END_DT
		,COALESCE(RCRD_TRM_DT,'9999-12-31')::TIMESTAMP as END_DTM
FROM TRAC_RPGW.DIM_PARTICIPANT PRT
LEFT OUTER JOIN (SELECT UPPER(TRIM(SRC_FLD_VAL)) AS SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(TRIM(SRC_CDE)) = 'TRAC' AND UPPER(TRIM(SRC_FLD_NM)) = 'STT_CD' AND UPPER(TRIM(TRNSLT_FLD_NM)) = 'STATE CODE') SDT1
 ON SDT1.SRC_FLD_VAL = UPPER(TRIM(PRT.STT_CD))
LEFT OUTER JOIN (SELECT UPPER(TRIM(SRC_FLD_VAL)) AS SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(TRIM(SRC_CDE)) = 'TRAC' AND UPPER(TRIM(SRC_FLD_NM)) = 'RSDNC_LCTN_CD' AND UPPER(TRIM(TRNSLT_FLD_NM)) = 'COUNTRY CODE') SDT2
 ON SDT2.SRC_FLD_VAL = UPPER(TRIM(PRT.RSDNC_LCTN_CD))
LEFT JOIN edw_audit.etl_batch_audit_vw ADT
	ON ADT.record_aligner = 1
	and ADT.batch_name = 'Trac_to_CIP'
) DRVD

LEFT JOIN (SELECT TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, TGT.END_DT, TGT.CURRENT_ROW_IND, TGT.CHECK_SUM, TGT.SOURCE_SYSTEM_ID
	FROM EDW.DIM_ADDRESS TGT
	LEFT OUTER JOIN (SELECT DIM_ADDRESS_NATURAL_KEY_HASH_UUID, END_DT, CURRENT_ROW_IND, CHECK_SUM, SOURCE_SYSTEM_ID
		FROM EDW_WORK.TRAC_DIM_ADDRESS
		WHERE CURRENT_ROW_IND= TRUE
		AND END_DT='9999-12-31') WRK
	ON TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID = WRK.DIM_ADDRESS_NATURAL_KEY_HASH_UUID::UUID
	AND TGT.CHECK_SUM <> WRK.CHECK_SUM::UUID
	WHERE WRK.DIM_ADDRESS_NATURAL_KEY_HASH_UUID IS NULL
	UNION
	SELECT DIM_ADDRESS_NATURAL_KEY_HASH_UUID::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID, END_DT, CURRENT_ROW_IND, CHECK_SUM::UUID AS CHECK_SUM, SOURCE_SYSTEM_ID
	FROM EDW_WORK.TRAC_DIM_ADDRESS) TGT
ON TGT.CURRENT_ROW_IND= TRUE
AND TGT.END_DT='9999-12-31'
--AND TGT.SOURCE_SYSTEM_ID = '203'
AND TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID = DRVD.DIM_ADDRESS_NATURAL_KEY_HASH_UUID

WHERE CASE WHEN TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM <> DRVD.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U');

--BENEFICIARY
/* BENEFICIARY - Select to capture insert of hist. records */
INSERT INTO EDW_WORK.TRAC_DIM_ADDRESS(DIM_ADDRESS_NATURAL_KEY_HASH_UUID, ATTENTION_LINE_TXT, ADDRESS_STREET_1_TXT, ADDRESS_STREET_2_TXT, ADDRESS_STREET_3_TXT, ADDRESS_STREET_4_TXT, CITY_NM, STATE_CDE, ZIP_CDE, ZIP_6_9_CDE, ZIP_10_13_CDE, COUNTRY_CDE, ADDRESS_VALIDATION_CDE, 
	BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, CURRENT_ROW_IND, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND)
SELECT DRVD.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, DRVD.ATTENTION_LINE_TXT, DRVD.ADDRESS_STREET_1_TXT,DRVD.ADDRESS_STREET_2_TXT,DRVD.ADDRESS_STREET_3_TXT,
	DRVD.ADDRESS_STREET_4_TXT,DRVD.CITY_NM,DRVD.STATE_CDE,DRVD.ZIP_CDE,DRVD.ZIP_6_9_CDE,DRVD.ZIP_10_13_CDE,DRVD.COUNTRY_CDE,DRVD.ADDRESS_VALIDATION_CDE,DRVD.BEGIN_DT, 
	DRVD.BEGIN_DTM,DRVD.ROW_PROCESS_DTM,DRVD.AUDIT_ID, DRVD.LOGICAL_DELETE_IND, DRVD.CHECK_SUM, CASE WHEN ROW_NUMBER() OVER (PARTITION BY DRVD.DIM_ADDRESS_NATURAL_KEY_HASH_UUID ORDER BY DRVD.END_DTM desc, DRVD.END_DT desc) = 1 and DRVD.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END::BOOLEAN AS CURRENT_ROW_IND,
	DRVD.END_DT, DRVD.END_DTM, DRVD.SOURCE_SYSTEM_ID, DRVD.RESTRICTED_ROW_IND
	FROM (SELECT DISTINCT UUID_GEN(PREHASH_VALUE(CLEAN_STRING(''),CLEAN_STRING(ADDRSS_LN_1), CLEAN_STRING(ADDRSS_LN_2), 
		 CLEAN_STRING(ADDRSS_LN_3), CLEAN_STRING(''),CLEAN_STRING(CITY_NM), CLEAN_STRING(SDT1.TRNSLT_FLD_VAL), CLEAN_STRING(ZIP_CD), 
		 CLEAN_STRING(ZIP_PLUS_4_CD), CLEAN_STRING(''), CLEAN_STRING(SDT2.TRNSLT_FLD_VAL)))::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID
		,CLEAN_STRING('') AS ATTENTION_LINE_TXT
		,CLEAN_STRING(ADDRSS_LN_1) AS ADDRESS_STREET_1_TXT
		, CLEAN_STRING(ADDRSS_LN_2) AS ADDRESS_STREET_2_TXT
		, CLEAN_STRING(ADDRSS_LN_3) AS ADDRESS_STREET_3_TXT
		, CLEAN_STRING('') AS ADDRESS_STREET_4_TXT
		, CLEAN_STRING(CITY_NM) AS CITY_NM
		, CLEAN_STRING(SDT1.TRNSLT_FLD_VAL) AS STATE_CDE
		, CLEAN_STRING(ZIP_CD) AS ZIP_CDE
		, CLEAN_STRING(ZIP_PLUS_4_CD) AS ZIP_6_9_CDE
		, CLEAN_STRING('') AS ZIP_10_13_CDE
		, CLEAN_STRING(SDT2.TRNSLT_FLD_VAL) AS COUNTRY_CDE
		,CLEAN_STRING('') AS ADDRESS_VALIDATION_CDE
		,HASH_GEN(PREHASH_VALUE(CLEAN_STRING('')))::UUID AS CHECK_SUM
		,RCRD_EFFCTV_DT::TIMESTAMP as BEGIN_DTM
		,RCRD_EFFCTV_DT::DATE as BEGIN_DT
		,CURRENT_TIMESTAMP as ROW_PROCESS_DTM
		,ADT.audit_id as AUDIT_ID
		,'203' as SOURCE_SYSTEM_ID
		,'F'::boolean as RESTRICTED_ROW_IND
		,'F'::boolean as LOGICAL_DELETE_IND
		,COALESCE(RCRD_TRM_DT,'9999-12-31')::DATE as END_DT
		,COALESCE(RCRD_TRM_DT,'9999-12-31')::TIMESTAMP as END_DTM
FROM TRAC_RPGW.DIM_BENEFICIARY BEN
LEFT OUTER JOIN (SELECT UPPER(TRIM(SRC_FLD_VAL)) AS SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(TRIM(SRC_CDE)) = 'TRAC' AND UPPER(TRIM(SRC_FLD_NM)) = 'STT_CD' AND UPPER(TRIM(TRNSLT_FLD_NM)) = 'STATE CODE') SDT1
 ON SDT1.SRC_FLD_VAL = UPPER(TRIM(BEN.STT_CD))
LEFT OUTER JOIN (SELECT UPPER(TRIM(SRC_FLD_VAL)) AS SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(TRIM(SRC_CDE)) = 'TRAC' AND UPPER(TRIM(SRC_FLD_NM)) = 'RSDNC_LCTN_CD' AND UPPER(TRIM(TRNSLT_FLD_NM)) = 'COUNTRY CODE') SDT2
 ON SDT2.SRC_FLD_VAL = UPPER(TRIM(BEN.RSDNC_LCTN_CD))
LEFT JOIN edw_audit.etl_batch_audit_vw ADT
	ON ADT.record_aligner = 1
	and ADT.batch_name = 'Trac_to_CIP'
) DRVD

LEFT JOIN (SELECT TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, TGT.END_DT, TGT.CURRENT_ROW_IND, TGT.CHECK_SUM, TGT.SOURCE_SYSTEM_ID
	FROM EDW.DIM_ADDRESS TGT
	LEFT OUTER JOIN (SELECT DIM_ADDRESS_NATURAL_KEY_HASH_UUID, END_DT, CURRENT_ROW_IND, CHECK_SUM, SOURCE_SYSTEM_ID
		FROM EDW_WORK.TRAC_DIM_ADDRESS
		WHERE CURRENT_ROW_IND= TRUE
		AND END_DT='9999-12-31') WRK
	ON TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID = WRK.DIM_ADDRESS_NATURAL_KEY_HASH_UUID::UUID
	AND TGT.CHECK_SUM <> WRK.CHECK_SUM::UUID
	WHERE WRK.DIM_ADDRESS_NATURAL_KEY_HASH_UUID IS NULL
	UNION
	SELECT DIM_ADDRESS_NATURAL_KEY_HASH_UUID::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID, END_DT, CURRENT_ROW_IND, CHECK_SUM::UUID AS CHECK_SUM, SOURCE_SYSTEM_ID
	FROM EDW_WORK.TRAC_DIM_ADDRESS) TGT
ON TGT.CURRENT_ROW_IND= TRUE
AND TGT.END_DT='9999-12-31'
--AND TGT.SOURCE_SYSTEM_ID = '203'
AND TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID = DRVD.DIM_ADDRESS_NATURAL_KEY_HASH_UUID

WHERE CASE WHEN TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM <> DRVD.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U');

--EMPLOYEE
/* EMPLOYEE - Select to capture insert of hist. records */
INSERT INTO EDW_WORK.TRAC_DIM_ADDRESS(DIM_ADDRESS_NATURAL_KEY_HASH_UUID, ATTENTION_LINE_TXT, ADDRESS_STREET_1_TXT, ADDRESS_STREET_2_TXT, ADDRESS_STREET_3_TXT, ADDRESS_STREET_4_TXT, CITY_NM, STATE_CDE, ZIP_CDE, ZIP_6_9_CDE, ZIP_10_13_CDE, COUNTRY_CDE, ADDRESS_VALIDATION_CDE, 
	BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, CURRENT_ROW_IND, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND)
SELECT DRVD.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, DRVD.ATTENTION_LINE_TXT, DRVD.ADDRESS_STREET_1_TXT,DRVD.ADDRESS_STREET_2_TXT,DRVD.ADDRESS_STREET_3_TXT,
	DRVD.ADDRESS_STREET_4_TXT,DRVD.CITY_NM,DRVD.STATE_CDE,DRVD.ZIP_CDE,DRVD.ZIP_6_9_CDE,DRVD.ZIP_10_13_CDE,DRVD.COUNTRY_CDE,DRVD.ADDRESS_VALIDATION_CDE,DRVD.BEGIN_DT, 
	DRVD.BEGIN_DTM,DRVD.ROW_PROCESS_DTM,DRVD.AUDIT_ID, DRVD.LOGICAL_DELETE_IND, DRVD.CHECK_SUM, CASE WHEN ROW_NUMBER() OVER (PARTITION BY DRVD.DIM_ADDRESS_NATURAL_KEY_HASH_UUID ORDER BY DRVD.END_DTM desc, DRVD.END_DT desc) = 1 and DRVD.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END::BOOLEAN AS CURRENT_ROW_IND,
	DRVD.END_DT, DRVD.END_DTM, DRVD.SOURCE_SYSTEM_ID, DRVD.RESTRICTED_ROW_IND
	FROM (SELECT DISTINCT UUID_GEN(PREHASH_VALUE(CLEAN_STRING(''),CLEAN_STRING(ADDRSS_LN_1), CLEAN_STRING(ADDRSS_LN_2), 
		 CLEAN_STRING(ADDRSS_LN_3), CLEAN_STRING(''),CLEAN_STRING(CITY_NM), CLEAN_STRING(SDT1.TRNSLT_FLD_VAL), CLEAN_STRING(ZIP_CD), 
		 CLEAN_STRING(ZIP_PLUS_4_CD), CLEAN_STRING(''), CLEAN_STRING(SDT2.TRNSLT_FLD_VAL)))::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID
		,CLEAN_STRING('') AS ATTENTION_LINE_TXT
		,CLEAN_STRING(ADDRSS_LN_1) AS ADDRESS_STREET_1_TXT
		, CLEAN_STRING(ADDRSS_LN_2) AS ADDRESS_STREET_2_TXT
		, CLEAN_STRING(ADDRSS_LN_3) AS ADDRESS_STREET_3_TXT
		, CLEAN_STRING('') AS ADDRESS_STREET_4_TXT
		, CLEAN_STRING(CITY_NM) AS CITY_NM
		, CLEAN_STRING(SDT1.TRNSLT_FLD_VAL) AS STATE_CDE
		, CLEAN_STRING(ZIP_CD) AS ZIP_CDE
		, CLEAN_STRING(ZIP_PLUS_4_CD) AS ZIP_6_9_CDE
		, CLEAN_STRING('') AS ZIP_10_13_CDE
		, CLEAN_STRING(SDT2.TRNSLT_FLD_VAL) AS COUNTRY_CDE
		,CLEAN_STRING('') AS ADDRESS_VALIDATION_CDE
		,HASH_GEN(PREHASH_VALUE(CLEAN_STRING('')))::UUID AS CHECK_SUM
		,RCRD_EFFCTV_DT::TIMESTAMP as BEGIN_DTM
		,RCRD_EFFCTV_DT::DATE as BEGIN_DT
		,CURRENT_TIMESTAMP as ROW_PROCESS_DTM
		,ADT.audit_id as AUDIT_ID
		,'203' as SOURCE_SYSTEM_ID
		,'F'::boolean as RESTRICTED_ROW_IND
		,'F'::boolean as LOGICAL_DELETE_IND
		,COALESCE(RCRD_TRM_DT,'9999-12-31')::DATE as END_DT
		,COALESCE(RCRD_TRM_DT,'9999-12-31')::TIMESTAMP as END_DTM
FROM TRAC_RPGW.DIM_EMPLOYEE EMP
LEFT OUTER JOIN (SELECT UPPER(TRIM(SRC_FLD_VAL)) AS SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(TRIM(SRC_CDE)) = 'TRAC' AND UPPER(TRIM(SRC_FLD_NM)) = 'STT_CD' AND UPPER(TRIM(TRNSLT_FLD_NM)) = 'STATE CODE') SDT1
 ON SDT1.SRC_FLD_VAL = UPPER(TRIM(EMP.STT_CD))
LEFT OUTER JOIN (SELECT UPPER(TRIM(SRC_FLD_VAL)) AS SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(TRIM(SRC_CDE)) = 'TRAC' AND UPPER(TRIM(SRC_FLD_NM)) = 'RSDNC_LCTN_CD' AND UPPER(TRIM(TRNSLT_FLD_NM)) = 'COUNTRY CODE') SDT2
 ON SDT2.SRC_FLD_VAL = UPPER(TRIM(EMP.RSDNC_LCTN_CD))
LEFT JOIN edw_audit.etl_batch_audit_vw ADT
	ON ADT.record_aligner = 1
	and ADT.batch_name = 'Trac_to_CIP'
) DRVD

LEFT JOIN (SELECT TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, TGT.END_DT, TGT.CURRENT_ROW_IND, TGT.CHECK_SUM, TGT.SOURCE_SYSTEM_ID
	FROM EDW.DIM_ADDRESS TGT
	LEFT OUTER JOIN (SELECT DIM_ADDRESS_NATURAL_KEY_HASH_UUID, END_DT, CURRENT_ROW_IND, CHECK_SUM, SOURCE_SYSTEM_ID
		FROM EDW_WORK.TRAC_DIM_ADDRESS
		WHERE CURRENT_ROW_IND= TRUE
		AND END_DT='9999-12-31') WRK
	ON TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID = WRK.DIM_ADDRESS_NATURAL_KEY_HASH_UUID::UUID
	AND TGT.CHECK_SUM <> WRK.CHECK_SUM::UUID
	WHERE WRK.DIM_ADDRESS_NATURAL_KEY_HASH_UUID IS NULL
	UNION
	SELECT DIM_ADDRESS_NATURAL_KEY_HASH_UUID::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID, END_DT, CURRENT_ROW_IND, CHECK_SUM::UUID AS CHECK_SUM, SOURCE_SYSTEM_ID
	FROM EDW_WORK.TRAC_DIM_ADDRESS) TGT
ON TGT.CURRENT_ROW_IND= TRUE
AND TGT.END_DT='9999-12-31'
--AND TGT.SOURCE_SYSTEM_ID = '203'
AND TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID = DRVD.DIM_ADDRESS_NATURAL_KEY_HASH_UUID

WHERE CASE WHEN TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM <> DRVD.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U');