

/* Truncation of the work table */
TRUNCATE TABLE EDW_WORK.TRAC_DIM_AGREEMENT;

--------------------

/* Select to capture insert and update records */

-- DIM_SPONSOR_COMPANY --

INSERT INTO EDW_WORK.TRAC_DIM_AGREEMENT (DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, AGREEMENT_NR_PFX, AGREEMENT_NR, AGREEMENT_NR_SFX, AGREEMENT_SOURCE_CDE, AGREEMENT_TYPE_CDE, MASTER_CONTRACT_GROUP_ID, SPONSOR_ID, PLAN_ID, SUBSCRIBER_ID, PARTICIPANT_ID, ICU_ID, MASTER_CONTRACT_GROUP_NM_NATIONAL_DESC, PLAN_NM_1_TXT, PLAN_NM_2_TXT, PLAN_NM_3_TXT, SUBSCRIBER_NR, AGREEMENT_STATUS_CDE, AGREEMENT_STATUS_REASON_CDE, ALLOW_ROLLOVER_IND, APPLICATION_SUBMIT_DT, BENEFICIARIES_RECORDED_IND, CONVERSION_EXPIRED_IND, CONVERSION_ELIGIBILITY_START_DT, CONVERSION_ELIGIBILITY_END_DT, DEFAULT_VOLUNTARY_DEFERRAL_RT, ENROLLMENT_DT, ENROLLMENT_ELIGIBILITY_DT, ENROLLMENT_START_DT, ENROLLMENT_END_DT, ENROLLMENT_STATUS_CDE, ENROLLMENT_TYPE_CDE, FACE_AMT, INTERNAL_PLAN_ID, ISSUE_DT, PARTICIPATION_DT, SOLICITATION_DT, SOLICITATION_IND, TAFT_HARTLY_IND, ELECTRONIC_CONTRIBUTION_CHANGE_IND, PRE_TAX_AUTO_INCREASE_CONTRIBUTION_RT,
	BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND, CURRENT_ROW_IND)
SELECT DRVD.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, DRVD.AGREEMENT_NR_PFX, DRVD.AGREEMENT_NR, DRVD.AGREEMENT_NR_SFX, DRVD.AGREEMENT_SOURCE_CDE, DRVD.AGREEMENT_TYPE_CDE, DRVD.MASTER_CONTRACT_GROUP_ID, DRVD.SPONSOR_ID, DRVD.PLAN_ID, DRVD.SUBSCRIBER_ID, DRVD.PARTICIPANT_ID, DRVD.ICU_ID, DRVD.MASTER_CONTRACT_GROUP_NM_NATIONAL_DESC, DRVD.PLAN_NM_1_TXT, DRVD.PLAN_NM_2_TXT, DRVD.PLAN_NM_3_TXT, DRVD.SUBSCRIBER_NM, DRVD.AGREEMENT_STATUS_CDE, DRVD.AGREEMENT_STATUS_REASON_CDE, DRVD.ALLOW_ROLLOVER_IND, DRVD.APPLICATION_SUBMIT_DT, DRVD.BENEFICIARIES_RECORDED_IND, DRVD.CONVERSION_EXPIRED_IND, DRVD.CONVERSION_ELIGIBILITY_START_DT, DRVD.CONVERSION_ELIGIBILITY_END_DT, DRVD.DEFAULT_VOLUNTARY_DEFERRAL_RT, DRVD.ENROLLMENT_DT, DRVD.ENROLLMENT_ELIGIBILITY_DT, DRVD.ENROLLMENT_START_DT, DRVD.ENROLLMENT_END_DT, DRVD.ENROLLMENT_STATUS_CDE, DRVD.ENROLLMENT_TYPE_CDE, DRVD.FACE_AMT, DRVD.INTERNAL_PLAN_ID, DRVD.ISSUE_DT AS ISSUE_DT, DRVD.PARTICIPATION_DT, DRVD.SOLICITATION_DT, DRVD.SOLICITATION_IND, DRVD.TAFT_HARTLY_IND, DRVD.ELECTRONIC_CONTRIBUTION_CHANGE_IND, DRVD.PRE_TAX_AUTO_INCREASE_CONTRIBUTION_RT,
	DRVD.BEGIN_DT, DRVD.BEGIN_DTM, CURRENT_TIMESTAMP as ROW_PROCESS_DTM, DRVD.AUDIT_ID, DRVD.LOGICAL_DELETE_IND, DRVD.CHECK_SUM, DRVD.END_DT, DRVD.END_DTM, DRVD.SOURCE_SYSTEM_ID, DRVD.RESTRICTED_ROW_IND
	, CASE WHEN ROW_NUMBER() OVER (PARTITION BY DRVD.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID ORDER BY DRVD.END_DTM desc, DRVD.END_DT desc) = 1 and DRVD.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END::BOOLEAN AS CURRENT_ROW_IND
FROM (SELECT DISTINCT uuid_gen(PREHASH_VALUE('', COALESCE(DECODE(LENGTH(BTRIM(ICU_ID)),0,'~',BTRIM(ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(SPNSR_CMPNY_ID::INTEGER),'~')::varchar, '', CLEAN_STRING('TRAC'), CLEAN_STRING('MCA')))::UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID

, CLEAN_STRING('') as AGREEMENT_NR_PFX
, COALESCE(DECODE(LENGTH(BTRIM(ICU_ID)),0,'~',BTRIM(ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(SPNSR_CMPNY_ID::INTEGER),'~') AS AGREEMENT_NR
, CLEAN_STRING('') as  AGREEMENT_NR_SFX
, CLEAN_STRING('TRAC') AS AGREEMENT_SOURCE_CDE
, CLEAN_STRING('MCA') AS AGREEMENT_TYPE_CDE

, COALESCE(DECODE(LENGTH(BTRIM(ICU_ID)),0,'~',BTRIM(ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(SPNSR_CMPNY_ID::INTEGER),'~') AS MASTER_CONTRACT_GROUP_ID
, TO_CHAR(SPNSR_CMPNY_ID::INTEGER) AS SPONSOR_ID
, CLEAN_STRING('') as PLAN_ID
, CLEAN_STRING('') as SUBSCRIBER_ID
, CLEAN_STRING('') as PARTICIPANT_ID
, CLEAN_STRING(ICU_ID) AS ICU_ID
, CLEAN_STRING(SPNSR_CMPNY_NM) AS MASTER_CONTRACT_GROUP_NM_NATIONAL_DESC
, CLEAN_STRING('') as PLAN_NM_1_TXT
, CLEAN_STRING('') as PLAN_NM_2_TXT
, CLEAN_STRING('') as PLAN_NM_3_TXT
, CLEAN_STRING('') as SUBSCRIBER_NM
, CLEAN_STRING('') as AGREEMENT_STATUS_CDE
, CLEAN_STRING('') as AGREEMENT_STATUS_REASON_Cde
, NULL as ALLOW_ROLLOVER_IND
, NULL as APPLICATION_SUBMIT_DT
, NULL as BENEFICIARIES_RECORDED_IND
, NULL as CONVERSION_EXPIRED_IND
, NULL as CONVERSION_ELIGIBILITY_START_DT
, NULL as CONVERSION_ELIGIBILITY_END_DT
, NULL as DEFAULT_VOLUNTARY_DEFERRAL_RT
, NULL as ENROLLMENT_DT
, NULL as ENROLLMENT_ELIGIBILITY_DT
, NULL as ENROLLMENT_START_DT
, NULL as ENROLLMENT_END_DT
, CLEAN_STRING('') as ENROLLMENT_STATUS_CDE
, CLEAN_STRING('') as ENROLLMENT_TYPE_CDE
, NULL as FACE_AMT
, CLEAN_STRING('') as INTERNAL_PLAN_ID
, NULL as ISSUE_DT
, NULL as PARTICIPATION_DT
, NULL as SOLICITATION_DT
, NULL as SOLICITATION_IND
, NULL as TAFT_HARTLY_IND
, NULL as ELECTRONIC_CONTRIBUTION_CHANGE_IND
, NULL as PRE_TAX_AUTO_INCREASE_CONTRIBUTION_RT
		
		, hash_gen(prehash_value(COALESCE(DECODE(LENGTH(BTRIM(ICU_ID)),0,'~',BTRIM(ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(SPNSR_CMPNY_ID::INTEGER),'~')::varchar, SPNSR_CMPNY_ID::varchar, '', '', '', ICU_ID::varchar, SPNSR_CMPNY_NM::varchar, '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL))::UUID AS CHECK_SUM
		, ADT.audit_id as AUDIT_ID
		,'203' as SOURCE_SYSTEM_ID
		, 'F'::boolean as RESTRICTED_ROW_IND
		, 'F'::boolean as LOGICAL_DELETE_IND
		, RCRD_EFFCTV_DT::timestamp as BEGIN_DTM
		, RCRD_EFFCTV_DT::date as BEGIN_DT
		, RCRD_TRM_DT::timestamp as END_DTM
		, RCRD_TRM_DT::date as END_DT

	FROM TRAC_RPGW.DIM_SPONSOR_COMPANY
	
	LEFT JOIN edw_audit.etl_batch_audit_vw ADT
	ON ADT.record_aligner = 1
	and ADT.batch_name = 'Trac_to_CIP'
	WHERE UPPER(ACTV_RCRD_IND) = 'Y'
AND CLEAN_STRING(ICU_ID) NOT IN ('~','00002','-1') AND CLEAN_STRING(ICU_ID) IS NOT NULL) DRVD

LEFT JOIN (SELECT DIM_AGREEMENT_NATURAL_KEY_HASH_UUID::UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, END_DT, CURRENT_ROW_IND, CHECK_SUM::UUID AS CHECK_SUM
	FROM EDW_WORK.TRAC_DIM_AGREEMENT) TGT
ON TGT.CURRENT_ROW_IND= TRUE
AND TGT.END_DT='9999-12-31'
AND TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID = DRVD.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID

WHERE CASE WHEN TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM <> DRVD.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U');

--------------------

-- DIM_PLAN --

/* Select to capture insert and update records */
INSERT INTO EDW_WORK.TRAC_DIM_AGREEMENT (DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, AGREEMENT_NR_PFX, AGREEMENT_NR, AGREEMENT_NR_SFX, AGREEMENT_SOURCE_CDE, AGREEMENT_TYPE_CDE, MASTER_CONTRACT_GROUP_ID, SPONSOR_ID, PLAN_ID, SUBSCRIBER_ID, PARTICIPANT_ID, ICU_ID, MASTER_CONTRACT_GROUP_NM_NATIONAL_DESC, PLAN_NM_1_TXT, PLAN_NM_2_TXT, PLAN_NM_3_TXT, SUBSCRIBER_NR, AGREEMENT_STATUS_CDE, AGREEMENT_STATUS_REASON_CDE, ALLOW_ROLLOVER_IND, APPLICATION_SUBMIT_DT, BENEFICIARIES_RECORDED_IND, CONVERSION_EXPIRED_IND, CONVERSION_ELIGIBILITY_START_DT, CONVERSION_ELIGIBILITY_END_DT, DEFAULT_VOLUNTARY_DEFERRAL_RT, ENROLLMENT_DT, ENROLLMENT_ELIGIBILITY_DT, ENROLLMENT_START_DT, ENROLLMENT_END_DT, ENROLLMENT_STATUS_CDE, ENROLLMENT_TYPE_CDE, FACE_AMT, INTERNAL_PLAN_ID, ISSUE_DT, PARTICIPATION_DT, SOLICITATION_DT, SOLICITATION_IND, TAFT_HARTLY_IND, ELECTRONIC_CONTRIBUTION_CHANGE_IND, PRE_TAX_AUTO_INCREASE_CONTRIBUTION_RT,
	BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND, CURRENT_ROW_IND)
SELECT DRVD.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, DRVD.AGREEMENT_NR_PFX, DRVD.AGREEMENT_NR, DRVD.AGREEMENT_NR_SFX, DRVD.AGREEMENT_SOURCE_CDE, DRVD.AGREEMENT_TYPE_CDE, DRVD.MASTER_CONTRACT_GROUP_ID, DRVD.SPONSOR_ID, DRVD.PLAN_ID, DRVD.SUBSCRIBER_ID, DRVD.PARTICIPANT_ID, DRVD.ICU_ID, DRVD.MASTER_CONTRACT_GROUP_NM_NATIONAL_DESC, DRVD.PLAN_NM_1_TXT, DRVD.PLAN_NM_2_TXT, DRVD.PLAN_NM_3_TXT, DRVD.SUBSCRIBER_NM, DRVD.AGREEMENT_STATUS_CDE, DRVD.AGREEMENT_STATUS_REASON_CDE, DRVD.ALLOW_ROLLOVER_IND, DRVD.APPLICATION_SUBMIT_DT, DRVD.BENEFICIARIES_RECORDED_IND, DRVD.CONVERSION_EXPIRED_IND, DRVD.CONVERSION_ELIGIBILITY_START_DT, DRVD.CONVERSION_ELIGIBILITY_END_DT, DRVD.DEFAULT_VOLUNTARY_DEFERRAL_RT, DRVD.ENROLLMENT_DT, DRVD.ENROLLMENT_ELIGIBILITY_DT, DRVD.ENROLLMENT_START_DT, DRVD.ENROLLMENT_END_DT, DRVD.ENROLLMENT_STATUS_CDE, DRVD.ENROLLMENT_TYPE_CDE, DRVD.FACE_AMT, DRVD.INTERNAL_PLAN_ID, DRVD.ISSUE_DT AS ISSUE_DT, DRVD.PARTICIPATION_DT, DRVD.SOLICITATION_DT, DRVD.SOLICITATION_IND, DRVD.TAFT_HARTLY_IND, DRVD.ELECTRONIC_CONTRIBUTION_CHANGE_IND, DRVD.PRE_TAX_AUTO_INCREASE_CONTRIBUTION_RT,
	DRVD.BEGIN_DT, DRVD.BEGIN_DTM, CURRENT_TIMESTAMP as ROW_PROCESS_DTM, DRVD.AUDIT_ID, DRVD.LOGICAL_DELETE_IND, DRVD.CHECK_SUM, DRVD.END_DT, DRVD.END_DTM, DRVD.SOURCE_SYSTEM_ID, DRVD.RESTRICTED_ROW_IND
	, CASE WHEN ROW_NUMBER() OVER (PARTITION BY DRVD.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID ORDER BY DRVD.END_DTM desc, DRVD.END_DT desc) = 1 and DRVD.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END::BOOLEAN AS CURRENT_ROW_IND
FROM (SELECT DISTINCT uuid_gen(PREHASH_VALUE('', COALESCE(DECODE(LENGTH(BTRIM(PLAN.ICU_ID)),0,'~',BTRIM(PLAN.ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(PLAN.SPNSR_CMPNY_ID::INTEGER),'~')  || '|' || COALESCE(DECODE(LENGTH(BTRIM(PLAN_ID)),0,'~',BTRIM(PLAN.PLAN_ID)),'~')::varchar, '', CLEAN_STRING('TRAC'), CLEAN_STRING('PSA')))::UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID
	
, CLEAN_STRING('') as AGREEMENT_NR_PFX
, COALESCE(DECODE(LENGTH(BTRIM(PLAN.ICU_ID)),0,'~',BTRIM(PLAN.ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(SPN.SPNSR_CMPNY_ID::INTEGER),'~')  || '|' || COALESCE(DECODE(LENGTH(BTRIM(PLAN.PLAN_ID)),0,'~',BTRIM(PLAN.PLAN_ID)),'~')  AS AGREEMENT_NR
, CLEAN_STRING('') as AGREEMENT_NR_SFX
, CLEAN_STRING('TRAC') AS AGREEMENT_SOURCE_CDE
, CLEAN_STRING('PSA') AS AGREEMENT_TYPE_CDE

, COALESCE(DECODE(LENGTH(BTRIM(PLAN.ICU_ID)),0,'~',BTRIM(PLAN.ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(PLAN.SPNSR_CMPNY_ID::INTEGER),'~') AS MASTER_CONTRACT_GROUP_ID
, TO_CHAR(PLAN.SPNSR_CMPNY_ID::INTEGER) AS SPONSOR_ID
, CLEAN_STRING(PLAN.PLAN_ID) AS PLAN_ID
, CLEAN_STRING('') as SUBSCRIBER_ID
, CLEAN_STRING('') as PARTICIPANT_ID
, CLEAN_STRING(PLAN.ICU_ID) AS ICU_ID
, CLEAN_STRING(SPNSR_CMPNY_NM) AS MASTER_CONTRACT_GROUP_NM_NATIONAL_DESC
, CLEAN_STRING(PLAN_NM) AS PLAN_NM_1_TXT
, CLEAN_STRING(PLAN_NM_2) AS PLAN_NM_2_TXT
, CLEAN_STRING(PLAN_NM_3) AS PLAN_NM_3_TXT
, CLEAN_STRING('') as SUBSCRIBER_NM
, CLEAN_STRING(SDT1.TRNSLT_FLD_VAL) AS AGREEMENT_STATUS_CDE
, CLEAN_STRING(SDT2.TRNSLT_FLD_VAL) AS AGREEMENT_STATUS_REASON_CDE
, NULL as ALLOW_ROLLOVER_IND
, NULL as APPLICATION_SUBMIT_DT
, NULL as BENEFICIARIES_RECORDED_IND
, NULL as CONVERSION_EXPIRED_IND
, NULL as CONVERSION_ELIGIBILITY_START_DT
, NULL as CONVERSION_ELIGIBILITY_END_DT
, DFLT_VLNTRY_DFRRL_PCT AS DEFAULT_VOLUNTARY_DEFERRAL_RT
, NULL as ENROLLMENT_DT
, NULL as ENROLLMENT_ELIGIBILITY_DT
, NULL as ENROLLMENT_START_DT
, NULL as ENROLLMENT_END_DT
, CLEAN_STRING('') as ENROLLMENT_STATUS_CDE
, CLEAN_STRING('') as ENROLLMENT_TYPE_CDE
, NULL as FACE_AMT
, CLEAN_STRING(INTRNL_PLAN_ID) AS INTERNAL_PLAN_ID
, NULL as ISSUE_DT
, NULL as PARTICIPATION_DT
, NULL as SOLICITATION_DT
, NULL as SOLICITATION_IND
, NULL as TAFT_HARTLY_IND
, NULL as ELECTRONIC_CONTRIBUTION_CHANGE_IND
, PRE_TAX_CNTRBTN_INCRS_RT AS PRE_TAX_AUTO_INCREASE_CONTRIBUTION_RT
		
		, hash_gen(prehash_value(COALESCE(DECODE(LENGTH(BTRIM(PLAN.ICU_ID)),0,'~',BTRIM(PLAN.ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(SPN.SPNSR_CMPNY_ID::INTEGER),'~')::varchar, PLAN.SPNSR_CMPNY_ID::varchar, PLAN.PLAN_ID::varchar, '', '', PLAN.ICU_ID::varchar, SPNSR_CMPNY_NM::varchar, PLAN_NM, PLAN_NM_2, PLAN_NM_3, '', SDT1.TRNSLT_FLD_VAL::varchar, SDT2.TRNSLT_FLD_VAL::varchar, NULL, NULL, NULL, NULL, NULL, NULL, DFLT_VLNTRY_DFRRL_PCT::varchar, NULL, NULL, NULL, NULL, '', '', NULL, INTRNL_PLAN_ID::varchar, NULL, NULL, NULL, NULL, NULL, NULL, PRE_TAX_CNTRBTN_INCRS_RT::varchar))::UUID AS CHECK_SUM
		, ADT.audit_id as AUDIT_ID
		,'203' as SOURCE_SYSTEM_ID
		, 'F'::boolean as RESTRICTED_ROW_IND
		, 'F'::boolean as LOGICAL_DELETE_IND
		, PLAN.RCRD_EFFCTV_DT::timestamp as BEGIN_DTM
		, PLAN.RCRD_EFFCTV_DT::date as BEGIN_DT
		, PLAN.RCRD_TRM_DT::timestamp as END_DTM
		, PLAN.RCRD_TRM_DT::date as END_DT

	FROM TRAC_RPGW.DIM_PLAN PLAN
LEFT OUTER JOIN TRAC_RPGW.DIM_SPONSOR_COMPANY SPN
 ON PLAN.ICU_ID = SPN.ICU_ID
 AND PLAN.SPNSR_CMPNY_ID = SPN.SPNSR_CMPNY_ID
LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(BTRIM(SRC_CDE)) = 'TRAC' AND UPPER(BTRIM(SRC_TBL_NM)) = 'DIM_PLAN' AND UPPER(BTRIM(SRC_FLD_NM)) =  'PLAN_STTS_CD' AND UPPER(BTRIM(TRNSLT_FLD_NM)) =  'STATUS CODE') SDT1
 ON CLEAN_STRING(SDT1.SRC_FLD_VAL) = CLEAN_STRING(PLAN.PLAN_STTS_CD)
LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(BTRIM(SRC_CDE)) = 'TRAC' AND UPPER(BTRIM(SRC_TBL_NM)) = 'DIM_PLAN' AND UPPER(BTRIM(SRC_FLD_NM)) =  'PLAN_STTS_CD' AND UPPER(BTRIM(TRNSLT_FLD_NM)) =  'STATUS REASON CODE') SDT2
 ON CLEAN_STRING(SDT2.SRC_FLD_VAL) = CLEAN_STRING(PLAN.PLAN_STTS_CD)

	LEFT JOIN edw_audit.etl_batch_audit_vw ADT
	ON ADT.record_aligner = 1
	and ADT.batch_name = 'Trac_to_CIP'
WHERE UPPER(PLAN.ACTV_RCRD_IND) = 'Y'
AND UPPER(SPN.ACTV_RCRD_IND) = 'Y'
AND CLEAN_STRING(PLAN.ICU_ID) NOT IN ('~','00002','-1') AND CLEAN_STRING(PLAN.ICU_ID) IS NOT NULL ) DRVD

LEFT JOIN (SELECT DIM_AGREEMENT_NATURAL_KEY_HASH_UUID::UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, END_DT, CURRENT_ROW_IND, CHECK_SUM::UUID AS CHECK_SUM
	FROM EDW_WORK.TRAC_DIM_AGREEMENT) TGT
ON TGT.CURRENT_ROW_IND= TRUE
AND TGT.END_DT='9999-12-31'
AND TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID = DRVD.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID

WHERE CASE WHEN TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM <> DRVD.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U');

	
--------------------

-- DIM_DIM_PARTICIPANT --

/* Select to capture insert and update records */
INSERT INTO EDW_WORK.TRAC_DIM_AGREEMENT (DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, AGREEMENT_NR_PFX, AGREEMENT_NR, AGREEMENT_NR_SFX, AGREEMENT_SOURCE_CDE, AGREEMENT_TYPE_CDE, MASTER_CONTRACT_GROUP_ID, SPONSOR_ID, PLAN_ID, SUBSCRIBER_ID, PARTICIPANT_ID, ICU_ID, MASTER_CONTRACT_GROUP_NM_NATIONAL_DESC, PLAN_NM_1_TXT, PLAN_NM_2_TXT, PLAN_NM_3_TXT, SUBSCRIBER_NR, AGREEMENT_STATUS_CDE, AGREEMENT_STATUS_REASON_CDE, ALLOW_ROLLOVER_IND, APPLICATION_SUBMIT_DT, BENEFICIARIES_RECORDED_IND, CONVERSION_EXPIRED_IND, CONVERSION_ELIGIBILITY_START_DT, CONVERSION_ELIGIBILITY_END_DT, DEFAULT_VOLUNTARY_DEFERRAL_RT, ENROLLMENT_DT, ENROLLMENT_ELIGIBILITY_DT, ENROLLMENT_START_DT, ENROLLMENT_END_DT, ENROLLMENT_STATUS_CDE, ENROLLMENT_TYPE_CDE, FACE_AMT, INTERNAL_PLAN_ID, ISSUE_DT, PARTICIPATION_DT, SOLICITATION_DT, SOLICITATION_IND, TAFT_HARTLY_IND, ELECTRONIC_CONTRIBUTION_CHANGE_IND, PRE_TAX_AUTO_INCREASE_CONTRIBUTION_RT,
	BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND, CURRENT_ROW_IND)
SELECT DRVD.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, DRVD.AGREEMENT_NR_PFX, DRVD.AGREEMENT_NR, DRVD.AGREEMENT_NR_SFX, DRVD.AGREEMENT_SOURCE_CDE, DRVD.AGREEMENT_TYPE_CDE, DRVD.MASTER_CONTRACT_GROUP_ID, DRVD.SPONSOR_ID, DRVD.PLAN_ID, DRVD.SUBSCRIBER_ID, DRVD.PARTICIPANT_ID, DRVD.ICU_ID, DRVD.MASTER_CONTRACT_GROUP_NM_NATIONAL_DESC, DRVD.PLAN_NM_1_TXT, DRVD.PLAN_NM_2_TXT, DRVD.PLAN_NM_3_TXT, DRVD.SUBSCRIBER_NM, DRVD.AGREEMENT_STATUS_CDE, DRVD.AGREEMENT_STATUS_REASON_CDE, DRVD.ALLOW_ROLLOVER_IND, DRVD.APPLICATION_SUBMIT_DT, DRVD.BENEFICIARIES_RECORDED_IND, DRVD.CONVERSION_EXPIRED_IND, DRVD.CONVERSION_ELIGIBILITY_START_DT, DRVD.CONVERSION_ELIGIBILITY_END_DT, DRVD.DEFAULT_VOLUNTARY_DEFERRAL_RT, DRVD.ENROLLMENT_DT, DRVD.ENROLLMENT_ELIGIBILITY_DT, DRVD.ENROLLMENT_START_DT, DRVD.ENROLLMENT_END_DT, DRVD.ENROLLMENT_STATUS_CDE, DRVD.ENROLLMENT_TYPE_CDE, DRVD.FACE_AMT, DRVD.INTERNAL_PLAN_ID, DRVD.ISSUE_DT AS ISSUE_DT, DRVD.PARTICIPATION_DT, DRVD.SOLICITATION_DT, DRVD.SOLICITATION_IND, DRVD.TAFT_HARTLY_IND, DRVD.ELECTRONIC_CONTRIBUTION_CHANGE_IND, DRVD.PRE_TAX_AUTO_INCREASE_CONTRIBUTION_RT,
	DRVD.BEGIN_DT, DRVD.BEGIN_DTM, CURRENT_TIMESTAMP as ROW_PROCESS_DTM, DRVD.AUDIT_ID, DRVD.LOGICAL_DELETE_IND, DRVD.CHECK_SUM, DRVD.END_DT, DRVD.END_DTM, DRVD.SOURCE_SYSTEM_ID, DRVD.RESTRICTED_ROW_IND
	, CASE WHEN ROW_NUMBER() OVER (PARTITION BY DRVD.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID ORDER BY DRVD.END_DTM desc, DRVD.END_DT desc) = 1 and DRVD.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END::BOOLEAN AS CURRENT_ROW_IND
FROM (SELECT DISTINCT uuid_gen(PREHASH_VALUE('', COALESCE(DECODE(LENGTH(BTRIM(PRT.ICU_ID)),0,'~',BTRIM(PRT.ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(PRT.SPNSR_CMPNY_ID::INTEGER),'~') || '|' || COALESCE(DECODE(LENGTH(BTRIM(PRT.PLAN_ID)),0,'~',BTRIM(PRT.PLAN_ID)),'~')  || '|' || COALESCE(DECODE(LENGTH(BTRIM(PRT.PRTCPNT_ID)),0,'~',BTRIM(PRT.PRTCPNT_ID)),'~')::varchar, '', CLEAN_STRING('TRAC'), CLEAN_STRING('PCA')))::UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID
		
, CLEAN_STRING('') as AGREEMENT_NR_PFX
, COALESCE(DECODE(LENGTH(BTRIM(PRT.ICU_ID)),0,'~',BTRIM(PRT.ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(PRT.SPNSR_CMPNY_ID::INTEGER),'~') || '|' || COALESCE(DECODE(LENGTH(BTRIM(PRT.PLAN_ID)),0,'~',BTRIM(PRT.PLAN_ID)),'~')  || '|' || COALESCE(DECODE(LENGTH(BTRIM(PRT.PRTCPNT_ID)),0,'~',BTRIM(PRT.PRTCPNT_ID)),'~')  AS AGREEMENT_NR
, CLEAN_STRING('') as AGREEMENT_NR_SFX
, CLEAN_STRING('TRAC') AS AGREEMENT_SOURCE_CDE
, CLEAN_STRING('PCA') AS AGREEMENT_TYPE_CDE

, COALESCE(DECODE(LENGTH(BTRIM(PRT.ICU_ID)),0,'~',BTRIM(PRT.ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(PRT.SPNSR_CMPNY_ID::INTEGER),'~') AS MASTER_CONTRACT_GROUP_ID
, TO_CHAR(PRT.SPNSR_CMPNY_ID::INTEGER) AS SPONSOR_ID
, CLEAN_STRING(PRT.PLAN_ID) AS PLAN_ID
, CLEAN_STRING('') as SUBSCRIBER_ID
, CLEAN_STRING(PRT.PRTCPNT_ID) AS PARTICIPANT_ID
, CLEAN_STRING(PRT.ICU_ID) AS ICU_ID
, CLEAN_STRING(SPNSR_CMPNY_NM) AS MASTER_CONTRACT_GROUP_NM_NATIONAL_DESC
, CLEAN_STRING(PLAN_NM) AS PLAN_NM_1_TXT
, CLEAN_STRING(PLAN_NM_2) AS PLAN_NM_2_TXT
, CLEAN_STRING(PLAN_NM_3) AS PLAN_NM_3_TXT
, CLEAN_STRING('') as SUBSCRIBER_NM
, CLEAN_STRING(SDT1.TRNSLT_FLD_VAL) AS AGREEMENT_STATUS_CDE
, CLEAN_STRING(SDT2.TRNSLT_FLD_VAL) AS AGREEMENT_STATUS_REASON_CDE
, NULL as ALLOW_ROLLOVER_IND
, NULL as APPLICATION_SUBMIT_DT
, NULL as BENEFICIARIES_RECORDED_IND
, NULL as CONVERSION_EXPIRED_IND
, NULL as CONVERSION_ELIGIBILITY_START_DT
, NULL as CONVERSION_ELIGIBILITY_END_DT
, DFLT_VLNTRY_DFRRL_PCT AS DEFAULT_VOLUNTARY_DEFERRAL_RT
, PLAN_ENRLLMNT_DT AS ENROLLMENT_DT
, NULL as ENROLLMENT_ELIGIBILITY_DT
, NULL as ENROLLMENT_START_DT
, NULL as ENROLLMENT_END_DT
, CLEAN_STRING('') as ENROLLMENT_STATUS_CDE
, CLEAN_STRING('') as ENROLLMENT_TYPE_CDE
, NULL as FACE_AMT
, CLEAN_STRING(PRT.INTRNL_PLAN_ID) AS INTERNAL_PLAN_ID
, NULL as ISSUE_DT
, NULL as PARTICIPATION_DT
, NULL as SOLICITATION_DT
, NULL as SOLICITATION_IND
, NULL as TAFT_HARTLY_IND
, NULL as ELECTRONIC_CONTRIBUTION_CHANGE_IND
,PRE_TAX_CNTRBTN_INCRS_RT AS PRE_TAX_AUTO_INCREASE_CONTRIBUTION_RT
	
		, hash_gen(prehash_value(COALESCE(DECODE(LENGTH(BTRIM(PRT.ICU_ID)),0,'~',BTRIM(PRT.ICU_ID)),'~') || '|' || COALESCE(TO_CHAR(PRT.SPNSR_CMPNY_ID::INTEGER),'~')::varchar, PRT.SPNSR_CMPNY_ID::varchar, PRT.PLAN_ID::varchar, '', PRT.PRTCPNT_ID::varchar, PRT.ICU_ID::varchar, SPNSR_CMPNY_NM, PLAN_NM, PLAN_NM_2, PLAN_NM_3, '', SDT1.TRNSLT_FLD_VAL::varchar, SDT2.TRNSLT_FLD_VAL::varchar, NULL, NULL, NULL, NULL, NULL, NULL, DFLT_VLNTRY_DFRRL_PCT, PLAN_ENRLLMNT_DT::varchar, NULL, NULL, NULL, '', '', NULL, PRT.INTRNL_PLAN_ID::varchar, NULL, NULL, NULL, NULL, NULL, NULL,PRE_TAX_CNTRBTN_INCRS_RT::varchar))::UUID AS CHECK_SUM

		, ADT.audit_id as AUDIT_ID
		,'203' as SOURCE_SYSTEM_ID
		, 'F'::boolean as RESTRICTED_ROW_IND
		, 'F'::boolean as LOGICAL_DELETE_IND
		, PRT.RCRD_EFFCTV_DT::timestamp as BEGIN_DTM
		, PRT.RCRD_EFFCTV_DT::date as BEGIN_DT
		, PRT.RCRD_TRM_DT::timestamp as END_DTM
		, PRT.RCRD_TRM_DT::date as END_DT

	FROM TRAC_RPGW.DIM_PARTICIPANT PRT
LEFT OUTER JOIN TRAC_RPGW.DIM_PLAN PLAN
 ON PLAN.ICU_ID = PRT.ICU_ID
 AND PLAN.SPNSR_CMPNY_ID = PRT.SPNSR_CMPNY_ID
 AND PLAN.PLAN_ID = PRT.PLAN_ID
LEFT OUTER JOIN TRAC_RPGW.DIM_SPONSOR_COMPANY SPN
 ON PLAN.ICU_ID = SPN.ICU_ID
 AND PLAN.SPNSR_CMPNY_ID = SPN.SPNSR_CMPNY_ID
LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(BTRIM(SRC_CDE)) = 'TRAC' AND SRC_TBL_NM = 'DIM_PARTICIPANT' AND UPPER(BTRIM(SRC_FLD_NM)) = 'PARTCPNT_STTS_CD' AND UPPER(BTRIM(TRNSLT_FLD_NM)) = 'STATUS CODE') SDT1
 ON CLEAN_STRING(SDT1.SRC_FLD_VAL) = CLEAN_STRING(PRT.PRTCPNT_STTS_CD)
LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(BTRIM(SRC_CDE)) = 'TRAC' AND SRC_TBL_NM = 'DIM_PARTICIPANT' AND UPPER(BTRIM(SRC_FLD_NM)) = 'PARTCPNT_STTS_CD' AND UPPER(BTRIM(TRNSLT_FLD_NM)) = 'STATUS REASON CODE') SDT2
 ON CLEAN_STRING(SDT2.SRC_FLD_VAL) = CLEAN_STRING(PRT.PRTCPNT_STTS_CD)

 LEFT JOIN edw_audit.etl_batch_audit_vw ADT
	ON ADT.record_aligner = 1
	and ADT.batch_name = 'Trac_to_CIP'
	
	WHERE UPPER(PLAN.ACTV_RCRD_IND) = 'Y'
AND UPPER(SPN.ACTV_RCRD_IND) = 'Y'
AND UPPER(PRT.ACTV_RCRD_IND) = 'Y'
AND CLEAN_STRING(PRT.ICU_ID) NOT IN ('00002','-1') AND CLEAN_STRING(PRT.ICU_ID) IS NOT NULL) DRVD

LEFT JOIN (SELECT DIM_AGREEMENT_NATURAL_KEY_HASH_UUID::UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, END_DT, CURRENT_ROW_IND, CHECK_SUM::UUID AS CHECK_SUM
	FROM EDW_WORK.TRAC_DIM_AGREEMENT) TGT
ON TGT.CURRENT_ROW_IND= TRUE
AND TGT.END_DT='9999-12-31'
AND TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID = DRVD.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID

WHERE CASE WHEN TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM <> DRVD.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U');

	
--------------------

