/* TRUNCATION OF THE WORK TABLE */
TRUNCATE TABLE EDW_WORK.TRAC_REL_PARTY_ADDRESS;

/* PARTICIPANT SQL QUERY TO CAPTURE BOTH INSERT AND UPDATE RECORDS */
INSERT INTO EDW_WORK.TRAC_REL_PARTY_ADDRESS (DIM_ADDRESS_NATURAL_KEY_HASH_UUID, REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, DIM_PARTY_NATURAL_KEY_HASH_UUID, PRIMARY_ADDRESS_IND, BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND, CURRENT_ROW_IND)
SELECT SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID, SRC.PRIMARY_ADDRESS_IND, SRC.BEGIN_DT, SRC.BEGIN_DTM, CURRENT_TIMESTAMP as ROW_PROCESS_DTM, SRC.AUDIT_ID, SRC.LOGICAL_DELETE_IND, SRC.CHECK_SUM, SRC.END_DT, SRC.END_DTM, SRC.SOURCE_SYSTEM_ID, SRC.RESTRICTED_ROW_IND, CASE WHEN ROW_NUMBER() OVER (PARTITION BY SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID ORDER BY SRC.END_DTM desc, SRC.END_DT desc) = 1 and SRC.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END::BOOLEAN AS CURRENT_ROW_IND
FROM (SELECT DISTINCT HASH_GEN(PREHASH_VALUE(CLEAN_STRING(''), CLEAN_STRING(ADDRSS_LN_1), CLEAN_STRING(ADDRSS_LN_2), CLEAN_STRING(ADDRSS_LN_3), CLEAN_STRING(''), CLEAN_STRING(CITY_NM), CLEAN_STRING(SDT1.TRNSLT_FLD_VAL), CLEAN_STRING(ZIP_CD), CLEAN_STRING(ZIP_PLUS_4_CD), CLEAN_STRING(''), CLEAN_STRING(SDT2.TRNSLT_FLD_VAL)))::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(CLEAN_STRING('STDA')))::UUID AS REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(CLEAN_STRING('TRAC')))::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(XREF.PARTY_ID))::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID
		, NULL AS PRIMARY_ADDRESS_IND
		, RCRD_EFFCTV_DT::date as BEGIN_DT
		, RCRD_EFFCTV_DT::timestamp as BEGIN_DTM
		, ADT.AUDIT_ID AS AUDIT_ID
		, 'F'::boolean AS LOGICAL_DELETE_IND
		, HASH_GEN(CLEAN_STRING(NULL))::UUID AS CHECK_SUM
		, RCRD_TRM_DT::date as END_DT
		, RCRD_TRM_DT::timestamp as END_DTM
		, '203' AS SOURCE_SYSTEM_ID
		, 'F'::boolean AS RESTRICTED_ROW_IND
	FROM (SELECT DISTINCT PARTY_ID, SOR_PARTY_ID FROM EDW.PARTY_MASTER_OF_MASTERS_XREF WHERE PARTY_ID_TYPE_CDE = 'TRAC_PRTC_ID' AND LOGICAL_DELETE_IND = 'F'::BOOLEAN) XREF
	JOIN TRAC_RPGW.DIM_PARTICIPANT TRC
	ON XREF.SOR_PARTY_ID = CLEAN_STRING(TRC.icu_id||'_'||TRC.plan_id||'_'||TRC.prtcpnt_id)
	LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(BTRIM(SRC_CDE)) = 'TRAC' AND UPPER(BTRIM(SRC_FLD_NM)) = 'STT_CD' AND UPPER(BTRIM(TRNSLT_FLD_NM)) = 'STATE CODE') SDT1
	ON UPPER(BTRIM(SDT1.SRC_FLD_VAL)) = UPPER(BTRIM(TRC.STT_CD))
	LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(BTRIM(SRC_CDE)) = 'TRAC' AND UPPER(BTRIM(SRC_FLD_NM)) = 'RSDNC_LCTN_CD' AND UPPER(BTRIM(TRNSLT_FLD_NM)) = 'COUNTRY CODE') SDT2
	ON UPPER(BTRIM(SDT2.SRC_FLD_VAL)) = UPPER(BTRIM(TRC.RSDNC_LCTN_CD))
	LEFT OUTER JOIN EDW_AUDIT.ETL_BATCH_AUDIT_VW ADT
	ON ADT.BATCH_NAME = 'Trac_to_CIP'
	AND ADT.RECORD_ALIGNER =1) SRC

LEFT OUTER JOIN (SELECT DIM_ADDRESS_NATURAL_KEY_HASH_UUID::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID, REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID::UUID AS REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, DIM_PARTY_NATURAL_KEY_HASH_UUID::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID, CHECK_SUM::UUID AS CHECK_SUM, CURRENT_ROW_IND, END_DT
	FROM EDW_WORK.TRAC_REL_PARTY_ADDRESS) TGT
ON TGT.CURRENT_ROW_IND= TRUE
AND TGT.END_DT='9999-12-31'
AND TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID=SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID
AND TGT.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID=SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID
AND TGT.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID=SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
AND TGT.DIM_PARTY_NATURAL_KEY_HASH_UUID=SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID

WHERE CASE WHEN TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID IS NULL OR TGT.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID IS NULL OR TGT.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID IS NULL OR TGT.DIM_PARTY_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM <> SRC.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U');

/* BENE SQL QUERY TO CAPTURE BOTH INSERT AND UPDATE RECORDS */
INSERT INTO EDW_WORK.TRAC_REL_PARTY_ADDRESS(DIM_ADDRESS_NATURAL_KEY_HASH_UUID, REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, DIM_PARTY_NATURAL_KEY_HASH_UUID, PRIMARY_ADDRESS_IND, BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND, CURRENT_ROW_IND)
SELECT SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID, SRC.PRIMARY_ADDRESS_IND, SRC.BEGIN_DT, SRC.BEGIN_DTM, CURRENT_TIMESTAMP as ROW_PROCESS_DTM, SRC.AUDIT_ID, SRC.LOGICAL_DELETE_IND, SRC.CHECK_SUM, SRC.END_DT, SRC.END_DTM, SRC.SOURCE_SYSTEM_ID, SRC.RESTRICTED_ROW_IND, CASE WHEN ROW_NUMBER() OVER (PARTITION BY SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID ORDER BY SRC.END_DTM desc, SRC.END_DT desc) = 1 and SRC.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END::BOOLEAN AS CURRENT_ROW_IND
FROM (SELECT DISTINCT HASH_GEN(PREHASH_VALUE(CLEAN_STRING(''), CLEAN_STRING(ADDRSS_LN_1), CLEAN_STRING(ADDRSS_LN_2), CLEAN_STRING(ADDRSS_LN_3), CLEAN_STRING(''), CLEAN_STRING(CITY_NM), CLEAN_STRING(SDT1.TRNSLT_FLD_VAL), CLEAN_STRING(ZIP_CD), CLEAN_STRING(ZIP_PLUS_4_CD), CLEAN_STRING(''), CLEAN_STRING(SDT2.TRNSLT_FLD_VAL)))::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(CLEAN_STRING('STDA')))::UUID AS REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(CLEAN_STRING('TRAC')))::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(XREF.PARTY_ID))::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID
		, NULL AS PRIMARY_ADDRESS_IND
		, CAST(RCRD_EFFCTV_DT AS DATE)::date as BEGIN_DT
		, CAST(RCRD_EFFCTV_DT AS DATE)::timestamp as BEGIN_DTM
		, ADT.AUDIT_ID AS AUDIT_ID
		, 'F'::boolean AS LOGICAL_DELETE_IND
		, HASH_GEN(CLEAN_STRING(NULL))::UUID AS CHECK_SUM
		, CAST(RCRD_TRM_DT AS DATE)::date as END_DT
		, CAST(RCRD_EFFCTV_DT AS DATE)::timestamp as END_DTM
		, CLEAN_STRING('203') AS SOURCE_SYSTEM_ID
		, 'F'::boolean AS RESTRICTED_ROW_IND
	FROM (SELECT DISTINCT PARTY_ID, SOR_PARTY_ID FROM EDW.PARTY_MASTER_OF_MASTERS_XREF WHERE PARTY_ID_TYPE_CDE = 'TRAC_BEN_ID' AND LOGICAL_DELETE_IND = 'F'::BOOLEAN) XREF
	JOIN TRAC_RPGW.DIM_BENEFICIARY TRC
	ON XREF.SOR_PARTY_ID = CLEAN_STRING(TRC.icu_id||'_'||TRC.plan_id||'_'||TRC.prtcpnt_id||'_'||TRC.BNFCRY_ID)
	LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(BTRIM(SRC_CDE)) = 'TRAC' AND UPPER(BTRIM(SRC_FLD_NM)) = 'STT_CD' AND UPPER(BTRIM(TRNSLT_FLD_NM)) = 'STATE CODE') SDT1
	ON UPPER(BTRIM(SDT1.SRC_FLD_VAL)) = UPPER(BTRIM(TRC.STT_CD))
	LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(BTRIM(SRC_CDE)) = 'TRAC' AND UPPER(BTRIM(SRC_FLD_NM)) = 'RSDNC_LCTN_CD' AND UPPER(BTRIM(TRNSLT_FLD_NM)) = 'COUNTRY CODE') SDT2
	ON UPPER(BTRIM(SDT2.SRC_FLD_VAL)) = UPPER(BTRIM(TRC.RSDNC_LCTN_CD))
	LEFT OUTER JOIN EDW_AUDIT.ETL_BATCH_AUDIT_VW ADT
	ON ADT.BATCH_NAME = 'Trac_to_CIP'
	AND ADT.RECORD_ALIGNER =1) SRC

LEFT OUTER JOIN (SELECT DIM_ADDRESS_NATURAL_KEY_HASH_UUID::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID, REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID::UUID AS REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, DIM_PARTY_NATURAL_KEY_HASH_UUID::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID, CHECK_SUM::UUID AS CHECK_SUM, CURRENT_ROW_IND, END_DT
	FROM EDW_WORK.TRAC_REL_PARTY_ADDRESS) TGT
ON TGT.CURRENT_ROW_IND= TRUE
AND TGT.END_DT='9999-12-31'
AND TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID=SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID
AND TGT.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID=SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID
AND TGT.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID=SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
AND TGT.DIM_PARTY_NATURAL_KEY_HASH_UUID=SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID

WHERE CASE WHEN TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID IS NULL OR TGT.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID IS NULL OR TGT.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID IS NULL OR TGT.DIM_PARTY_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM <> SRC.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U');

/* EMP SQL QUERY TO CAPTURE BOTH INSERT AND UPDATE RECORDS */
INSERT INTO EDW_WORK.TRAC_REL_PARTY_ADDRESS (DIM_ADDRESS_NATURAL_KEY_HASH_UUID, REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, DIM_PARTY_NATURAL_KEY_HASH_UUID, PRIMARY_ADDRESS_IND, BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND, CURRENT_ROW_IND)
SELECT SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID, SRC.PRIMARY_ADDRESS_IND, SRC.BEGIN_DT, SRC.BEGIN_DTM, CURRENT_TIMESTAMP as ROW_PROCESS_DTM, SRC.AUDIT_ID, SRC.LOGICAL_DELETE_IND, SRC.CHECK_SUM, SRC.END_DT, SRC.END_DTM, SRC.SOURCE_SYSTEM_ID, SRC.RESTRICTED_ROW_IND, CASE WHEN ROW_NUMBER() OVER (PARTITION BY SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID ORDER BY SRC.END_DTM desc, SRC.END_DT desc) = 1 and SRC.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END::BOOLEAN AS CURRENT_ROW_IND 
FROM (SELECT DISTINCT HASH_GEN(PREHASH_VALUE(CLEAN_STRING(''), CLEAN_STRING(ADDRSS_LN_1), CLEAN_STRING(ADDRSS_LN_2), CLEAN_STRING(ADDRSS_LN_3), CLEAN_STRING(''), CLEAN_STRING(CITY_NM), CLEAN_STRING(SDT1.TRNSLT_FLD_VAL), CLEAN_STRING(ZIP_CD), CLEAN_STRING(ZIP_PLUS_4_CD), CLEAN_STRING(''), CLEAN_STRING(SDT2.TRNSLT_FLD_VAL)))::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(CLEAN_STRING('STDA')))::UUID AS REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(CLEAN_STRING('TRAC')))::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(XREF.PARTY_ID))::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID
		, NULL AS PRIMARY_ADDRESS_IND
		, CAST(RCRD_EFFCTV_DT AS DATE)::date as BEGIN_DT
		, CAST(RCRD_EFFCTV_DT AS DATE)::timestamp as BEGIN_DTM
		, ADT.AUDIT_ID AS AUDIT_ID
		, 'F'::boolean AS LOGICAL_DELETE_IND
		, HASH_GEN(CLEAN_STRING(NULL))::UUID AS CHECK_SUM
		, CAST(RCRD_TRM_DT AS DATE)::date as END_DT
		, CAST(RCRD_EFFCTV_DT AS DATE)::timestamp as END_DTM
		, '203' AS SOURCE_SYSTEM_ID
		, 'F'::boolean AS RESTRICTED_ROW_IND
	FROM (SELECT DISTINCT PARTY_ID, SOR_PARTY_ID FROM EDW.PARTY_MASTER_OF_MASTERS_XREF WHERE PARTY_ID_TYPE_CDE = 'TRAC_EMP_ID' AND LOGICAL_DELETE_IND = 'F'::BOOLEAN) XREF
	JOIN TRAC_RPGW.DIM_EMPLOYEE TRC
	ON XREF.SOR_PARTY_ID = CLEAN_STRING(TRC.ICU_ID||'_'||TRC.AFFLT_CMPNY_ID||'_'||TRC.SPNSR_CMPNY_ID||'_'||TRC.EMPLY_TAX_ID)
	LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(BTRIM(SRC_CDE)) = 'TRAC' AND UPPER(BTRIM(SRC_FLD_NM)) = 'STT_CD' AND UPPER(BTRIM(TRNSLT_FLD_NM)) = 'STATE CODE') SDT1
	ON UPPER(BTRIM(SDT1.SRC_FLD_VAL)) = UPPER(BTRIM(TRC.STT_CD))
	LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(BTRIM(SRC_CDE)) = 'TRAC' AND UPPER(BTRIM(SRC_FLD_NM)) = 'RSDNC_LCTN_CD' AND UPPER(BTRIM(TRNSLT_FLD_NM)) = 'COUNTRY CODE') SDT2
	ON UPPER(BTRIM(SDT2.SRC_FLD_VAL)) = UPPER(BTRIM(TRC.RSDNC_LCTN_CD))
	LEFT OUTER JOIN EDW_AUDIT.ETL_BATCH_AUDIT_VW ADT
	ON ADT.BATCH_NAME = 'Trac_to_CIP'
	AND ADT.RECORD_ALIGNER =1) SRC

LEFT OUTER JOIN (SELECT DIM_ADDRESS_NATURAL_KEY_HASH_UUID::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID, REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID::UUID AS REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, DIM_PARTY_NATURAL_KEY_HASH_UUID::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID, CHECK_SUM::UUID AS CHECK_SUM, CURRENT_ROW_IND, END_DT
	FROM EDW_WORK.TRAC_REL_PARTY_ADDRESS) TGT
ON TGT.CURRENT_ROW_IND= TRUE
AND TGT.END_DT='9999-12-31'
AND TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID=SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID
AND TGT.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID=SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID
AND TGT.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID=SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
AND TGT.DIM_PARTY_NATURAL_KEY_HASH_UUID=SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID

WHERE CASE WHEN TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID IS NULL OR TGT.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID IS NULL OR TGT.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID IS NULL OR TGT.DIM_PARTY_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM <> SRC.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U');