/* Truncation of the work table */
TRUNCATE TABLE EDW_WORK.TRAC_DIM_ACCOUNT;

/* Capture insert and update records */
INSERT INTO EDW_WORK.TRAC_DIM_ACCOUNT
(DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, MASTER_CONTRACT_GROUP_ID, PLAN_ID, SUBSCRIBER_ID, PARTICIPANT_ID, ICU_ID, TOTAL_BALANCE_SHARE_AMT, TOTAL_BALANCE_CASH_AMT, ROLLOVER_IND, SUSPENSION_START_DT, SUSPENSION_END_DT, AUTO_DEFERRAL_IND, PRE_TAX_AUTO_INCREASE_ELECTION_IND, DEFERRAL_ENROLLMENT_PRE_TAX_AMT, DEFERRAL_ENROLLMENT_PRE_TAX_RT, DEFERRAL_ENROLLMENT_POST_TAX_AMT, DEFERRAL_ENROLLMENT_POST_TAX_RT,  DEFERRAL_ENROLLMENT_ROTH_AMT, DEFERRAL_ENROLLMENT_ROTH_RT, DEFERRAL_ENROLLMENT_TOTAL_RT, DEFERRAL_ENROLLMENT_TOTAL_AMT, DEFERRAL_ENROLLMENT_STATUS_CDE, EACA_PARTICIPATION_IND, EACA_OPT_OUT_DT, EACA_START_DT, QACA_PARTICIPATION_IND, QACA_OPT_OUT_DT, QACA_NEXT_DEFERRAL_INCREASE_DT, HIRE_DT, COMPENSATION_415_AMT, HIGHLY_COMPENSATED_EMPLOYEE_IND, KEY_EMPLOYEE_IND, EMPLOYEE_STATUS_CDE, BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, CURRENT_ROW_IND, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND)
SELECT DRVD.DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, DRVD.MASTER_CONTRACT_GROUP_ID, DRVD.PLAN_ID, DRVD.SUBSCRIBER_ID, DRVD.PARTICIPANT_ID, DRVD.ICU_ID, DRVD.TOTAL_BALANCE_SHARE_AMT, DRVD.TOTAL_BALANCE_CASH_AMT, DRVD.ROLLOVER_IND, DRVD.SUSPENSION_START_DT, DRVD.SUSPENSION_END_DT, DRVD.AUTO_DEFERRAL_IND, DRVD.PRE_TAX_AUTO_INCREASE_ELECTION_IND, DRVD.DEFERRAL_ENROLLMENT_PRE_TAX_AMT, DRVD.DEFERRAL_ENROLLMENT_PRE_TAX_RT, DRVD.DEFERRAL_ENROLLMENT_POST_TAX_AMT, DRVD.DEFERRAL_ENROLLMENT_POST_TAX_RT, DRVD.DEFERRAL_ENROLLMENT_ROTH_AMT, DRVD.DEFERRAL_ENROLLMENT_ROTH_RT, DRVD.DEFERRAL_ENROLLMENT_TOTAL_AMT, DRVD.DEFERRAL_ENROLLMENT_TOTAL_RT, DRVD.DEFERRAL_ENROLLMENT_STATUS_CDE, DRVD.EACA_PARTICIPATION_IND, DRVD.EACA_OPT_OUT_DT, DRVD.EACA_START_DT, DRVD.QACA_PARTICIPATION_IND, DRVD.QACA_OPT_OUT_DT, DRVD.QACA_NEXT_DEFERRAL_INCREASE_DT, DRVD.HIRE_DT, DRVD.COMPENSATION_415_AMT, DRVD.HIGHLY_COMPENSATED_EMPLOYEE_IND, DRVD.KEY_EMPLOYEE_IND, DRVD.EMPLOYEE_STATUS_CDE, 
CASE WHEN TGT.CHECK_SUM <> DRVD.CHECK_SUM THEN CURRENT_DATE ELSE DRVD.BEGIN_DT END AS BEGIN_DT, CASE WHEN TGT.CHECK_SUM <> DRVD.CHECK_SUM THEN CURRENT_DATE::timestamp ELSE DRVD.BEGIN_DTM END AS BEGIN_DTM, CURRENT_TIMESTAMP AS ROW_PROCESS_DTM, DRVD.AUDIT_ID, DRVD.LOGICAL_DELETE_IND, DRVD.CHECK_SUM, CASE WHEN ROW_NUMBER() OVER (PARTITION BY DRVD.DIM_ACCOUNT_NATURAL_KEY_HASH_UUID ORDER BY DRVD.END_DTM DESC, DRVD.END_DT DESC) = 1 and DRVD.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END::BOOLEAN AS CURRENT_ROW_IND, DRVD.END_DT, DRVD.END_DTM, DRVD.SOURCE_SYSTEM_ID, DRVD.RESTRICTED_ROW_IND 

FROM (
	SELECT   DIM_ACCOUNT_NATURAL_KEY_HASH_UUID::UUID, MASTER_CONTRACT_GROUP_ID, PLAN_ID, SUBSCRIBER_ID, PARTICIPANT_ID, ICU_ID,TOTAL_BALANCE_SHARE_AMT, TOTAL_BALANCE_CASH_AMT, ROLLOVER_IND, SUSPENSION_START_DT, SUSPENSION_END_DT, AUTO_DEFERRAL_IND,PRE_TAX_AUTO_INCREASE_ELECTION_IND, DEFERRAL_ENROLLMENT_PRE_TAX_AMT, DEFERRAL_ENROLLMENT_PRE_TAX_RT, DEFERRAL_ENROLLMENT_POST_TAX_AMT,DEFERRAL_ENROLLMENT_POST_TAX_RT, DEFERRAL_ENROLLMENT_ROTH_AMT, DEFERRAL_ENROLLMENT_ROTH_RT, DEFERRAL_ENROLLMENT_TOTAL_RT,DEFERRAL_ENROLLMENT_TOTAL_AMT, DEFERRAL_ENROLLMENT_STATUS_CDE, EACA_PARTICIPATION_IND, EACA_OPT_OUT_DT, EACA_START_DT, QACA_PARTICIPATION_IND,QACA_OPT_OUT_DT, QACA_NEXT_DEFERRAL_INCREASE_DT, HIRE_DT, COMPENSATION_415_AMT, HIGHLY_COMPENSATED_EMPLOYEE_IND, KEY_EMPLOYEE_IND,EMPLOYEE_STATUS_CDE, BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND
	, HASH_GEN(PREHASH_VALUE(MASTER_CONTRACT_GROUP_ID, PLAN_ID, SUBSCRIBER_ID, PARTICIPANT_ID, ICU_ID, TOTAL_BALANCE_SHARE_AMT, TOTAL_BALANCE_CASH_AMT, ROLLOVER_IND, SUSPENSION_START_DT, SUSPENSION_END_DT, AUTO_DEFERRAL_IND
	, PRE_TAX_AUTO_INCREASE_ELECTION_IND, DEFERRAL_ENROLLMENT_PRE_TAX_AMT, DEFERRAL_ENROLLMENT_PRE_TAX_RT, DEFERRAL_ENROLLMENT_POST_TAX_AMT, DEFERRAL_ENROLLMENT_POST_TAX_RT, DEFERRAL_ENROLLMENT_ROTH_AMT
	, DEFERRAL_ENROLLMENT_ROTH_RT, DEFERRAL_ENROLLMENT_TOTAL_RT, DEFERRAL_ENROLLMENT_TOTAL_AMT, DEFERRAL_ENROLLMENT_STATUS_CDE, EACA_PARTICIPATION_IND, EACA_OPT_OUT_DT, EACA_START_DT, QACA_PARTICIPATION_IND
	, QACA_OPT_OUT_DT, QACA_NEXT_DEFERRAL_INCREASE_DT, HIRE_DT, COMPENSATION_415_AMT, HIGHLY_COMPENSATED_EMPLOYEE_IND, KEY_EMPLOYEE_IND, EMPLOYEE_STATUS_CDE))::UUID AS CHECK_SUM, CURRENT_ROW_IND, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND 
	FROM (SELECT HASH_GEN(PREHASH_VALUE(PARTY_ROLE_CDE,PARTY_ID, AGREEMENT_SOURCE_CDE, AGREEMENT_TYPE_CDE, AGREEMENT_NR_PFX, AGREEMENT_NR, AGREEMENT_NR_SFX))::UUID AS DIM_ACCOUNT_NATURAL_KEY_HASH_UUID
		, MASTER_CONTRACT_GROUP_ID
		, PLAN_ID
		, CLEAN_STRING('') AS SUBSCRIBER_ID,PRTCPNT_ID AS PARTICIPANT_ID
		, ICU_ID
		, TOTAL_BALANCE_SHARE_AMT
		, TOTAL_BALANCE_CASH_AMT
		, ROLLOVER_IND
		, SUSPENSION_START_DT
		, SUSPENSION_END_DT
		, AUTO_DEFERRAL_IND
		, PRE_TAX_AUTO_INCREASE_ELECTION_IND
		, DEFERRAL_ENROLLMENT_PRE_TAX_AMT
		, DEFERRAL_ENROLLMENT_PRE_TAX_RT
		, DEFERRAL_ENROLLMENT_POST_TAX_AMT
		, DEFERRAL_ENROLLMENT_POST_TAX_RT
		, DEFERRAL_ENROLLMENT_ROTH_AMT
		, DEFERRAL_ENROLLMENT_ROTH_RT
		, CLEAN_STRING('') AS DEFERRAL_ENROLLMENT_TOTAL_AMT
		, CLEAN_STRING('') AS DEFERRAL_ENROLLMENT_TOTAL_RT
		, DEFERRAL_ENROLLMENT_STATUS_CDE
		, EACA_PARTICIPATION_IND
		, EACA_OPT_OUT_DT
		, EACA_START_DT
		, QACA_PARTICIPATION_IND
		, QACA_OPT_OUT_DT
		, QACA_NEXT_DEFERRAL_INCREASE_DT
		, HIRE_DT,CLEAN_STRING('') AS COMPENSATION_415_AMT
		, HIGHLY_COMPENSATED_EMPLOYEE_IND, KEY_EMPLOYEE_IND
		, EMPLOYEE_STATUS_CDE
		, COALESCE(RCRD_EFFCTV_DT,'0001-01-01')::DATE AS BEGIN_DT
		, COALESCE(RCRD_EFFCTV_DT,'0001-01-01')::TIMESTAMP AS BEGIN_DTM
		, CURRENT_TIMESTAMP AS ROW_PROCESS_DTM
		, ADT.AUDIT_ID AS AUDIT_ID, 'F'::BOOLEAN AS LOGICAL_DELETE_IND
		, 'T'::BOOLEAN AS CURRENT_ROW_IND
		, COALESCE(RCRD_TRM_DT,'9999-12-31')::DATE AS END_DT
		, COALESCE(RCRD_TRM_DT,'9999-12-31')::TIMESTAMP AS END_DTM
		, '203' AS SOURCE_SYSTEM_ID
		, 'F'::BOOLEAN AS RESTRICTED_ROW_IND
FROM (SELECT DISTINCT CLEAN_STRING('') AS AGREEMENT_NR_PFX, PREHASH_VALUE(CLEAN_STRING(TRC.ICU_ID),CLEAN_STRING(TO_CHAR(TRC.SPNSR_CMPNY_ID::INTEGER)),CLEAN_STRING(TRC.PLAN_ID),CLEAN_STRING(TRC.PRTCPNT_ID) ) AS AGREEMENT_NR, CLEAN_STRING('') AS AGREEMENT_NR_SFX, CLEAN_STRING('TRAC') AS AGREEMENT_SOURCE_CDE, CLEAN_STRING('PCA') AS AGREEMENT_TYPE_CDE, XREF.PARTY_ID AS PARTY_ID, CLEAN_STRING('PTCP') AS PARTY_ROLE_CDE, PREHASH_VALUE(CLEAN_STRING(TRC.ICU_ID),CLEAN_STRING(TO_CHAR(TRC.SPNSR_CMPNY_ID::INTEGER))) AS MASTER_CONTRACT_GROUP_ID, TRC.PLAN_ID, TRC.PRTCPNT_ID, TRC.ICU_ID, BAL.TOTAL_BALANCE_SHARE_AMT, BAL.TOTAL_BALANCE_CASH_AMT, (CASE WHEN ROLL.ICU_ID IS NOT NULL THEN 'Y' ELSE 'N' END)::BOOLEAN AS ROLLOVER_IND, TRC.SSPND_STRT_DT AS SUSPENSION_START_DT, TRC.SSPND_END_DT AS SUSPENSION_END_DT, (CASE WHEN PLAN.QLFD_PLAN_INCPTN_RT > 0 OR PLAN.PRE_TAX_CNTRBTN_INCRS_RT > 0 THEN 'T' ELSE 'F' END)::BOOLEAN AS AUTO_DEFERRAL_IND, (CASE WHEN UPPER(BTRIM(ENROLL.PRE_TAX_AUTO_INCRS_ELCTD_IND)) NOT IN ('Y','N') THEN CLEAN_STRING('') ELSE CLEAN_STRING(ENROLL.PRE_TAX_AUTO_INCRS_ELCTD_IND) END)::BOOLEAN AS PRE_TAX_AUTO_INCREASE_ELECTION_IND, ENROLL.PRE_TAX_ENRLLMNT_AMT AS DEFERRAL_ENROLLMENT_PRE_TAX_AMT, ENROLL.PRE_TAX_ENRLLMNT_RT AS DEFERRAL_ENROLLMENT_PRE_TAX_RT, ENROLL.POST_TAX_ENRLLMNT_AMT AS DEFERRAL_ENROLLMENT_POST_TAX_AMT, ENROLL.POST_TAX_ENRLLMNT_RT AS DEFERRAL_ENROLLMENT_POST_TAX_RT, ENROLL.ROTH_ELCTV_DFRRL_ENRLLMNT_AMT AS DEFERRAL_ENROLLMENT_ROTH_AMT, ENROLL.ROTH_ELCTV_DFRRL_ENRLLMNT_RT AS DEFERRAL_ENROLLMENT_ROTH_RT, ENROLL.ENRLLMNT_STTS_CD AS DEFERRAL_ENROLLMENT_STATUS_CDE, (CASE WHEN UPPER(BTRIM(ENROLL.EACA_PRTCPNT_IND)) NOT IN ('Y','N') THEN CLEAN_STRING('') ELSE CLEAN_STRING(ENROLL.EACA_PRTCPNT_IND) END)::BOOLEAN AS EACA_PARTICIPATION_IND, ENROLL.EACA_OPT_OUT_DT, ENROLL.EACA_STRT_DT AS EACA_START_DT, (CASE WHEN UPPER(BTRIM(ENROLL.QACA_PRTCPNT_IND)) NOT IN ('Y','N') THEN CLEAN_STRING('') ELSE CLEAN_STRING(ENROLL.QACA_PRTCPNT_IND) END)::BOOLEAN AS QACA_PARTICIPATION_IND, ENROLL.QACA_OPT_OUT_DT, ENROLL.QACA_NEXT_INCRS_DT AS QACA_NEXT_DEFERRAL_INCREASE_DT, EMP.HIRE_DT, CLEAN_STRING(EMP.HCE_IND)::BOOLEAN HIGHLY_COMPENSATED_EMPLOYEE_IND, CLEAN_STRING(EMP.KEY_EMPLY_IND)::BOOLEAN AS KEY_EMPLOYEE_IND, CLEAN_STRING(SDT1.TRNSLT_FLD_VAL) AS EMPLOYEE_STATUS_CDE, RCRD_EFFCTV_DT, RCRD_TRM_DT
	FROM (SELECT DISTINCT PARTY_ID, SOR_PARTY_ID FROM EDW.PARTY_MASTER_OF_MASTERS_XREF WHERE PARTY_ID_TYPE_CDE = 'TRAC_PRTC_ID' AND LOGICAL_DELETE_IND = 'F'::BOOLEAN) XREF
--Join to DIM_PARTICIPANT
JOIN (SELECT ICU_ID,AFFLT_CMPNY_ID, PLAN_ID,SPNSR_CMPNY_ID, PRTCPNT_ID, SSPND_STRT_DT, SSPND_END_DT, EMPLY_STTS_CD,EMPLY_TAX_ID  FROM TRAC_RPGW.DIM_PARTICIPANT WHERE UPPER(BTRIM(ACTV_RCRD_IND)) = 'Y') TRC
	ON CLEAN_STRING(XREF.SOR_PARTY_ID) = CLEAN_STRING(TRC.icu_id||'_'||TRC.plan_id||'_'||TRC.prtcpnt_id)
--join to DIM_PLAN
LEFT OUTER JOIN (SELECT ICU_ID, PLAN_ID,QLFD_PLAN_INCPTN_RT, PRE_TAX_CNTRBTN_INCRS_RT  FROM TRAC_RPGW.DIM_PLAN WHERE UPPER(BTRIM(ACTV_RCRD_IND)) = 'Y') PLAN
	ON TRC.ICU_ID = PLAN.ICU_ID
	AND TRC.PLAN_ID = PLAN.PLAN_ID
--Join to FACT_PRTCPNT_ASST_DTL to get most current balance information
LEFT OUTER JOIN (SELECT ICU_ID, PRTCPNT_ID, PLAN_ID, SUM(ASST_PSTN_AMT) AS TOTAL_BALANCE_CASH_AMT, SUM(SHR_BLNC_AMT) AS TOTAL_BALANCE_SHARE_AMT
    FROM TRAC_RPGW.FACT_PRTCPNT_ASST_DTL
    group by ICU_ID, PRTCPNT_ID, PLAN_ID) BAL
	ON TRC.ICU_ID = BAL.ICU_ID
	AND TRC.PLAN_ID = BAL.PLAN_ID
	AND TRC.PRTCPNT_ID = BAL.PRTCPNT_ID
--Join to VRU_ENROLLMENT_STATUS for deferral information
LEFT OUTER JOIN (SELECT *
    FROM (select ROW_NUMBER() OVER(PARTITION BY ICU_ID, PLAN_ID, PRTCPNT_ID ORDER BY RCRD_EFFCTV_DT DESC, VRU_ENRLLMNT_STTS_KEY DESC) AS RANKING
     , ICU_ID, PLAN_ID, PRTCPNT_ID, ENRLLMNT_STTS_CD
     , PRE_TAX_AUTO_INCRS_ELCTD_IND, PRE_TAX_ENRLLMNT_AMT, PRE_TAX_ENRLLMNT_RT
     , POST_TAX_ENRLLMNT_AMT, POST_TAX_ENRLLMNT_RT
     , ROTH_ELCTV_DFRRL_ENRLLMNT_AMT, ROTH_ELCTV_DFRRL_ENRLLMNT_RT
     , EACA_PRTCPNT_IND, EACA_OPT_OUT_DT, EACA_STRT_DT
     , QACA_PRTCPNT_IND, QACA_OPT_OUT_DT, QACA_NEXT_INCRS_DT
     , RCRD_EFFCTV_DT,RCRD_TRM_DT
    from TRAC_RPGW.DIM_VRU_ENROLLMENT_STATUS
    WHERE UPPER(BTRIM(ACTV_RCRD_IND)) = 'Y') T1
    WHERE RANKING = 1) ENROLL
	ON TRC.ICU_ID = ENROLL.ICU_ID
	AND TRC.PLAN_ID = ENROLL.PLAN_ID
	AND TRC.PRTCPNT_ID = ENROLL.PRTCPNT_ID

--Join to DIM EMPLOYEE
LEFT OUTER JOIN (SELECT ICU_ID, AFFLT_CMPNY_ID, SPNSR_CMPNY_ID, EMPLY_TAX_ID, HIRE_DT, HCE_IND, KEY_EMPLY_IND
    FROM TRAC_RPGW.DIM_EMPLOYEE WHERE UPPER(BTRIM(ACTV_RCRD_IND)) = 'Y') EMP
	ON TRC.ICU_ID = EMP.ICU_ID
	AND TRC.AFFLT_CMPNY_ID = EMP.AFFLT_CMPNY_ID
	AND TRC.SPNSR_CMPNY_ID = EMP.SPNSR_CMPNY_ID
	AND TRC.EMPLY_TAX_ID = EMP.EMPLY_TAX_ID
 
--Join to AHPS_MONEYTYPE to get data needed for rollover INDICATOR
LEFT OUTER JOIN (SELECT distinct ICU_ID, PLAN_ID, PRTCPNT_ID
    FROM TRAC_RPGW.FACT_PRTCPNT_ASST_DTL
    WHERE SRC_CD IN (128, 129, 155, 112, 182)) ROLL
	ON TRC.ICU_ID = ROLL.ICU_ID
	AND TRC.PLAN_ID = ROLL.PLAN_ID
	AND TRC.PRTCPNT_ID = ROLL.PRTCPNT_ID
 
LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE UPPER(BTRIM(SRC_CDE)) = 'TRAC' AND UPPER(BTRIM(SRC_TBL_NM)) = 'DIM_PARTICIPANT' AND UPPER(BTRIM(SRC_FLD_NM)) = 'EMPLOYEE_STTS_CD' AND UPPER(BTRIM(TRNSLT_FLD_NM)) = 'EMPLOYEE STATUS CODE') SDT1
	ON UPPER(BTRIM(SDT1.SRC_FLD_VAL)) = UPPER(BTRIM(TRC.EMPLY_STTS_CD)) ) T1
LEFT JOIN edw_audit.etl_batch_audit_vw ADT
	ON ADT.record_aligner = 1
	AND ADT.batch_name = 'Trac_to_CIP')T2
) DRVD

LEFT JOIN (SELECT DIM_ACCOUNT_NATURAL_KEY_HASH_UUID::UUID AS DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, END_DT, CURRENT_ROW_IND, CHECK_SUM::UUID AS CHECK_SUM
	FROM EDW_WORK.TRAC_DIM_ACCOUNT) TGT
ON TGT.CURRENT_ROW_IND= TRUE
AND TGT.END_DT='9999-12-31'
AND TGT.DIM_ACCOUNT_NATURAL_KEY_HASH_UUID = DRVD.DIM_ACCOUNT_NATURAL_KEY_HASH_UUID

WHERE CASE WHEN TGT.DIM_ACCOUNT_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM <> DRVD.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U');